# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S <- function(t, S_fun, S_params) {
    .Call(`_Functions_S`, t, S_fun, S_params)
}

integrand_H_obs <- function(r, S_fun, S_params, H_fun, H_params) {
    .Call(`_Functions_integrand_H_obs`, r, S_fun, S_params, H_fun, H_params)
}

H_obs <- function(t, S_fun, S_params, H_fun, H_params) {
    .Call(`_Functions_H_obs`, t, S_fun, S_params, H_fun, H_params)
}

Var_Fun <- function(t, n, pi, S_fun, S_params, H_fun, H_params, theta) {
    .Call(`_Functions_Var_Fun`, t, n, pi, S_fun, S_params, H_fun, H_params, theta)
}

W <- function(t, w_shape1, w_shape2, tau) {
    .Call(`_Functions_W`, t, w_shape1, w_shape2, tau)
}

Sol <- function(tau, n, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta) {
    .Call(`_Functions_Sol`, tau, n, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta)
}

