# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S <- function(t, S_fun, S_params) {
    .Call(`_Functions_S`, t, S_fun, S_params)
}

f <- function(t, S_fun, S_params) {
    .Call(`_Functions_f`, t, S_fun, S_params)
}

H <- function(t, H_fun, H_params) {
    .Call(`_Functions_H`, t, H_fun, H_params)
}

h <- function(t, H_fun, H_params) {
    .Call(`_Functions_h`, t, H_fun, H_params)
}

Y <- function(t, n, pi, S_fun, S_params, H_fun, H_params, theta) {
    .Call(`_Functions_Y`, t, n, pi, S_fun, S_params, H_fun, H_params, theta)
}

Var_Fun <- function(t, n, pi, S_fun, S_params, H_fun, H_params, theta) {
    .Call(`_Functions_Var_Fun`, t, n, pi, S_fun, S_params, H_fun, H_params, theta)
}

W <- function(t, w_shape1, w_shape2, tau) {
    .Call(`_Functions_W`, t, w_shape1, w_shape2, tau)
}

Opt_Fun <- function(tau, n, pi, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta) {
    .Call(`_Functions_Opt_Fun`, tau, n, pi, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta)
}

Sol <- function(tau, n, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta) {
    .Call(`_Functions_Sol`, tau, n, S_fun, S_params, H_fun, H_params, w_shape1, w_shape2, theta)
}

